pinochle: MeldInstance.o MeldServices.o MeldsStorage.o Computer.o Human.o Player.o Card.o Deck.o Game.o GroupOfCards.o Pinochle.o PinochleException.o Round.o StringUtilities.o
	g++ -std=c++0x MeldInstance.o MeldServices.o MeldsStorage.o Computer.o Human.o Player.o Card.o Deck.o Game.o GroupOfCards.o Pinochle.o PinochleException.o Round.o StringUtilities.o -o pinochle

MeldInstance.o: MeldInstance.cpp
	g++ -std=c++0x -c MeldInstance.cpp

MeldServices.o: MeldServices.cpp
	g++ -std=c++0x -c MeldServices.cpp

MeldsStorage.o: MeldsStorage.cpp
	g++ -std=c++0x -c MeldsStorage.cpp

Computer.o: Computer.cpp
	g++ -std=c++0x -c Computer.cpp

Human.o: Human.cpp
	g++ -std=c++0x -c Human.cpp

Player.o: Player.cpp
	g++ -std=c++0x -c Player.cpp

Card.o: Card.cpp
	g++ -std=c++0x -c Card.cpp

Deck.o: Deck.cpp
	g++ -std=c++0x -c Deck.cpp

Game.o: Game.cpp
	g++ -std=c++0x -c Game.cpp

GroupOfCards.o: GroupOfCards.cpp
	g++ -std=c++0x -c GroupOfCards.cpp

Pinochle.o: Pinochle.cpp
	g++ -std=c++0x -c Pinochle.cpp

PinochleException.o: PinochleException.cpp
	g++ -std=c++0x -c PinochleException.cpp

Round.o: Round.cpp
	g++ -std=c++0x -c Round.cpp

StringUtilities.o: StringUtilities.cpp
	g++ -std=c++0x -c StringUtilities.cpp

clean:
	rm *.o math